### ISSUE TITLE
[Validation] - GPSD Python Utilities fail on unicode socket encoding errors

### ISSUE THREAD

**Issue by jr1221** [Northeastern-Electric-Racing/Siren#84]
### Observed Behavior

For scripts that use gps (ex. ubxtool).
```
Traceback (most recent call last):
  File "/root/./gps_test.py", line 9, in <module>
    session = gps.gps(mode=gps.WATCH_ENABLE)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gps/gps.py", line 606, in __init__
  File "/usr/lib/python3.11/site-packages/gps/client.py", line 66, in __init__
  File "/usr/lib/python3.11/site-packages/gps/client.py", line 87, in connect
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
LookupError: unknown encoding: idna
```

### Expected Behavior

No error, full use of library.

Blocks #gps

### Steps to Reproduce

1. import gps
2. watch gps using gps.gps()

**Comment by jr1221** [comment]
Adding unicodedata python3 core module fixes this!!
